apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJUMmRoZEc5eU9tZG9jRjlsVWxCTVVYWk5ZVXRuVlZGbVluTXphRzUxVlc5amFtVXhSREZVUVhFelVIUnVTVzA9IgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson
